Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: 7daystodie-
    SupplierDeployMetadata:
      ArtifactRelation:
        'm-bp1bx1br89nv53czvt7p':
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: ${Artifact.EcsImage.ArtifactVersion}
    TemplateConfigs:
      - Name: 快速部署
        Url: 'ros_templates/7daystodie.yaml'
        AllowedRegions:
          - cn-beijing
          - cn-zhangjiakou
          - cn-huhehaote
          - cn-wulanchabu
          - cn-hangzhou
          - cn-shanghai
          - cn-shenzhen
          - cn-heyuan
          - cn-guangzhou
          - cn-chengdu
          - cn-hongkong
          - ap-northeast-1
          - ap-northeast-2
          - ap-southeast-1
          - ap-southeast-3
          - ap-southeast-6
          - ap-southeast-5
          - ap-southeast-7
          - us-east-1
          - us-west-1
          - eu-west-1
          - me-east-1
          - eu-central-1
          - cn-qingdao
      - Name: 迁移到计算巢
        Url: 'ros_templates/7daystodie-exist.yaml'
        AllowedRegions:
          - cn-beijing
          - cn-zhangjiakou
          - cn-huhehaote
          - cn-wulanchabu
          - cn-hangzhou
          - cn-shanghai
          - cn-shenzhen
          - cn-heyuan
          - cn-guangzhou
          - cn-chengdu
          - cn-hongkong
          - ap-northeast-1
          - ap-northeast-2
          - ap-southeast-1
          - ap-southeast-3
          - ap-southeast-6
          - ap-southeast-5
          - ap-southeast-7
          - us-east-1
          - us-west-1
          - eu-west-1
          - me-east-1
          - eu-central-1
          - cn-qingdao
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: docker deploy
    Image: 'resources/icons/service_logo.png'
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: minecraft
    Description: Minecraft deploy
    ArtifactProperty:
      RegionId: ${ImageBuilder.EcsImage.RegionId}
      ImageId: ${ImageBuilder.EcsImage.SourceImageId}
    SupportRegionIds:
      - cn-beijing
      - cn-zhangjiakou
      - cn-huhehaote
      - cn-wulanchabu
      - cn-hangzhou
      - cn-shanghai
      - cn-shenzhen
      - cn-heyuan
      - cn-guangzhou
      - cn-chengdu
      - cn-hongkong
      - ap-northeast-1
      - ap-northeast-2
      - ap-southeast-1
      - ap-southeast-3
      - ap-southeast-6
      - ap-southeast-5
      - ap-southeast-7
      - us-east-1
      - us-west-1
      - eu-west-1
      - me-east-1
      - eu-central-1
      - cn-qingdao
ImageBuilder:
  EcsImage:
    RegionId: cn-hangzhou
    SourceImageId: m-bp18v4uy9djurq8fgo8r
    SystemDiskSize: 100
    InstanceType: ecs.c6.large
    InternetMaxBandwidthOut: 10
    CommandType: RunShellScript
    Timeout: 10800
    CommandContent: |-
        # 更新游戏
        $TaskName = "7DaysToDieServerAutoStart"
        Start-Process "C:\Program Files\7DaysToDieServer\steam\steamcmd.exe" -ArgumentList "+login anonymous +app_update 294420 validate +quit" -Wait

        # 启动游戏
        Start-ScheduledTask -TaskName $TaskName
        Start-Sleep -Seconds 60
