Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: 7daystodie-
    SupplierDeployMetadata:
      ArtifactRelation:
        'm-bp1bx1br89nv53czvt7p':
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: ${Artifact.EcsImage.ArtifactVersion}
    TemplateConfigs:
      - Name: 快速部署
        Url: 'ros_templates/7daystodie.yaml'
      - Name: 迁移到计算巢
        Url: 'ros_templates/7daystodie-exist.yaml'
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: docker deploy
    Image: 'resources/icons/service_logo.jpg'
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: 7DaysToDie
    Description: 7DaysToDie deploy
    ArtifactProperty:
      RegionId: ${ImageBuilder.EcsImage.RegionId}
      ImageId: ${ImageBuilder.EcsImage.SourceImageId}
ImageBuilder:
  EcsImage:
    RegionId: cn-shenzhen
    SourceImageId: m-wz99d1d64b6ae14p2vo0
    SystemDiskSize: 100
    InstanceType: ecs.c6.large
    InternetMaxBandwidthOut: 10
    CommandType: RunPowerShellScript
    Timeout: 10800
    CommandContent: |-
        # 更新游戏
        $TaskName = "7DaysToDieServerAutoStart"
        Start-Process "C:\Program Files\7DaysToDieServer\steam\steamcmd.exe" -ArgumentList "+login anonymous +app_update 294420 validate +quit" -Wait

        # 启动游戏
        Start-ScheduledTask -TaskName $TaskName
        Start-Sleep -Seconds 60
